.PHONY: test clean act_test connect test_autogenerated test_scenarios test_global
baseImage ?= quay.io/fedora/fedora-minimal:latest

feature ?= setup
clean:
	rm -rdf /tmp/${feature}
	rm -rdf /tmp/setup
	rm -rdf /tmp/devcontainercli
	@docker rmi $(docker images -q --filter=reference="vsc-home*" --format "{{.ID}}") -f || true
	docker volume prune -f
act: clean
	act workflow_dispatch --pull=false --workflows=.github/workflows/validate.yml --actor=$GITHUB_USERNAME

connect:
	docker exec -it $$(docker ps -lq) bash

test_autogenerated:
	devcontainer features test --skip-scenarios -f ${feature} -i ${baseImage} .

test_scenarios:
	devcontainer features test -f ${feature} --skip-autogenerated --skip-duplicated .

test_global:
	devcontainer features test --global-scenarios-only .

test: clean test_global

smoke:
	rm -rdf /tmp/init
	rm -rdf /tmp/home
	@docker rmi $(docker images -q --filter=reference="vsc-home*" --format "{{.ID}}") -f  &&\
	rm -rdf /tmp/init &&\
	rm -rdf /tmp/home || true
	docker volume prune -f
	@echo "Local Smoketest..."
	.github/actions/smoke-test/build.sh home
	.github/actions/smoke-test/test.sh home

# "tasks": [
#     {
#         "label": "make all",
#         "command": "make",
#         "type": "shell",
#         "presentation": {
#             "close": false
#         },
#         "group": {
#             "kind": "build",
#             "isDefault": false
#         }
#     },
#     {
#         "label": "make test",
#         "command": "make",
#         "type": "shell",
#         "args": [
#             "test"
#         ],
#         "presentation": {
#             "close": false
#         },
#         "group": {
#             "kind": "test",
#             "isDefault": true
#         }
#     },
#     {
#         "label": "make clean",
#         "command": "make",
#         "type": "shell",
#         "args": [
#             "clean"
#         ],
#         "presentation": {
#             "close": false
#         },
#         "group": {
#             "kind": "none",
#             "isDefault": false
#         }
#     },
#     {
#         "label": "make act",
#         "command": "act",
#         "type": "shell",
#         "args": [
#             "workflow_dispatch",
#             "--pull=false",
#             "--workflows=.github/workflows/validate.yml",
#             "--actor=$GITHUB_USERNAME"
#         ],
#         "presentation": {
#             "close": false
#         },
#         "group": {
#             "kind": "none",
#             "isDefault": false
#         }
#     }
# ]