.PHONY: test clean act_test connect test_autogenerated test_scenarios test_global
baseImage ?= quay.io/fedora/fedora-minimal:latest

feature ?= setup
clean:
	rm -rdf /tmp/${feature}
	rm -rdf /tmp/setup
	rm -rdf /tmp/devcontainercli
	@docker rmi $(docker images -q --filter=reference="vsc-home*" --format "{{.ID}}") -f || true
	docker volume prune -f
act: clean
	act workflow_dispatch --pull=false --workflows=.github/workflows/validate.yml --actor=$GITHUB_USERNAME

connect:
	docker exec -it $$(docker ps -lq) bash

test_autogenerated:
	devcontainer features test --skip-scenarios -f ${feature} -i ${baseImage} .

test_scenarios:
	devcontainer features test -f ${feature} --skip-autogenerated --skip-duplicated .

test_global:
	devcontainer features test --global-scenarios-only .

test: clean test_global